<?php
namespace dvlp\logTableAction\traits;

use dvlp\logTableAction\components\tableDependency\Dependency;
use dvlp\logTableAction\events\LogTableActionEvent;
use dvlp\logTableAction\models\LogTableAction;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;


/**
 * Логирование действий ActiveRecord
 * Class LogTableActionTrait
 * @package backend\modules\logTableAction\traits
 */
trait LogTableActionTrait
{
    private $deleteAllAtributes;
    private $dataChanged;

    private $isInit = false;

    protected function initLogTableAction()
    {
        if (!$this->isInit) {
            $this->on(LogTableActionEvent::EVENT_AFTER_INSERT,  [$this, 'lafterInsert']);
            $this->on(LogTableActionEvent::EVENT_AFTER_UPDATE,  [$this, 'lafterUpdate']);
            $this->on(LogTableActionEvent::EVENT_BEFORE_UPDATE,  [$this, 'lbeforeUpdate']);
            $this->on(LogTableActionEvent::EVENT_AFTER_STATIC_UPDATE_ALL,  [$this, 'lafterStaticUpdateAll']);
            $this->on(LogTableActionEvent::EVENT_BEFORE_STATIC_DELETE_ALL,  [$this, 'lbeforeStaticDeleteAll']);
            $this->on(LogTableActionEvent::EVENT_AFTER_STATIC_DELETE_ALL,  [$this, 'lafterStaticDeleteAll']);
            $this->isInit = true;
        }
    }


    /**
     * @param $attributes
     * @param string $condition
     * @param array $params
     * @return mixed
     */
    public static function updateAll($attributes, $condition = '', $params = [])
    {
        $event = new LogTableActionEvent();
        $event->attributes = $attributes;
        $event->condition = $condition;
        $event->params = $params;
        $model = new static(); // немнго херово в статике создавать оюъект, но trigger нужно вызывать только на объекте
        $model->trigger(LogTableActionEvent::EVENT_BEFORE_STATIC_UPDATE_ALL, $event );
        $result = parent::updateAll($attributes, $condition, $params); // TODO: Change the autogenerated stub
        if ($result > 0) {
            $model->trigger(LogTableActionEvent::EVENT_AFTER_STATIC_UPDATE_ALL, $event );
        }
        return $result;
    }

    /**
     * @param string $condition
     * @param array $params
     * @return mixed
     */
    public static function deleteAll($condition = null, $params = [])
    {
        $event = new LogTableActionEvent();
        $event->condition = $condition;
        $event->params = $params;
        $model = new static(); // немнго херово в статике создавать оюъект, но trigger нужно вызывать только на объекте
        $model->trigger(LogTableActionEvent::EVENT_BEFORE_STATIC_DELETE_ALL, $event );
        $result = parent::deleteAll($condition, $params); // TODO: Change the autogenerated stub
        if ($result > 0) {
            $model->trigger(LogTableActionEvent::EVENT_AFTER_STATIC_DELETE_ALL, $event );
        }
        return $result;
    }

    /**
     *
     */
    public function lbeforeUpdate()
    {
        $model = $this;
        $dataArray = (array)$model->getAttributes();
        $olDataArray = (array)$model->oldAttributes;
        $this->dataChanged = array_diff($olDataArray, $dataArray);
    }

    /**
     * Сохранение состояния таблицы
     */
    public function lafterInsert()
    {
        $model = $this;
        LogTableAction::saveLog(LogTableActionEvent::ACTION_INSERT, $model->getAttribute('id'), $model->tableName(), Json::encode($model->getAttributes()));
    }

    /**
     * Сохранение состояния таблицы
     */
    public function lafterUpdate()
    {
        $model = $this;
        LogTableAction::saveLog(LogTableActionEvent::ACTION_UPDATE, $model->getAttribute('id'), $model->tableName(), Json::encode($model->getAttributes()), Json::encode($this->dataChanged));
    }



    /**
     * @param LogTableActionEvent $event
     */
    public function lafterStaticUpdateAll(LogTableActionEvent $event)
    {
        $model = $this;
        LogTableAction::saveLog(LogTableActionEvent::ACTION_UPDATE_ALL, 0, $model->tableName(), Json::encode([
            'attributes' => $event->attributes,
            'condition' => $event->condition,
            'params' => $event->params,
        ]));
    }

    /**
     * @param LogTableActionEvent $event
     */
    public function lbeforeStaticDeleteAll(LogTableActionEvent $event)
    {
        $models = self::find()->andWhere($event->condition, $event->params)->all();
        $dep = new Dependency();
        foreach ($models as $model) {
            $attributes = $model->getAttributes();
            $attributes['dependency'] = $dep->getDependencyData($model->tableName(), $attributes);
            $this->deleteAllAtributes[] = $attributes;
        }

    }

    /**
     * @param LogTableActionEvent $event
     */
    public function lafterStaticDeleteAll(LogTableActionEvent $event)
    {
        if(!empty($this->deleteAllAtributes)) {
            foreach ($this->deleteAllAtributes as $attributes) {
                LogTableAction::saveLog(LogTableActionEvent::ACTION_DELETE_ALL, ArrayHelper::getValue($attributes, 'id'), $this->tableName(), Json::encode($attributes));
            }
        }
    }



}